#!/bin/bash
umount /mnt/cf >/dev/null 2>/dev/null
mount -t msdos /dev/hda1 /mnt/cf || exit 1
cd /
chown -R root:root etc root usr/local
chown root:root home
tar cvzf /mnt/cf/syscfg.tgz etc home root usr/local /usr/src/getsrc /var/www/html /var/spool/cron 
sync
umount /mnt/cf
exit 0
