#! /bin/sh

# !/bin/bash
#
# nodesetup.sh
#
CONFIGS=/etc/asterisk
TMP=/tmp

function die {
	echo "Fatal error: $1"
	exit 255
}

function promptnum
{
	ANSWER=""
	while [ -z $ANSWER  ] || [[ ! $ANSWER =~ [0-9]{1,}$ ]]
	do
        	echo -n "$1: "
        	read ANSWER
	done
}

CURCFG=

if [ -f /etc/init.d/pciradio ]
then
	CURCFG=pciradio
fi

if [ -f /etc/init.d/usbradio ]
then
	CURCFG=usbradio
fi

if [ -f /etc/init.d/simpleusb ]
then
	CURCFG=simpleusb
fi

if [ -z $CURCFG ]
then
	echo "Unknown current configuration"
	exit 1
fi

echo
echo "Current system configuration: $CURCFG"
echo

NEWCFG=

while [ -z $NEWCFG ]
do
	echo "Please choose one of the following:"
	echo
	echo "1) pciradio (QRV quad PCI radio card)"
	echo "2) usbradio (URI or USB fob, with DSP support)"
	echo "3) simpleusb (URI or USB fob, without DSP support)"
	echo "0) I dont want to change my configuration at this time"
	echo
	promptnum "Please make your selection now"
	echo
	if [ $ANSWER = "0" ]
	then
		echo "Configuration not modified"
		exit
	fi
	if [ $ANSWER = "1" ]
	then
		NEWCFG=pciradio
	fi
	if [ $ANSWER = "2" ]
	then
		NEWCFG=usbradio
	fi
	if [ $ANSWER = "3" ]
	then
		NEWCFG=simpleusb
	fi
done

if [ $CURCFG = $NEWCFG ]
then
	echo "Configuration is already $CURCFG, nothing to do"
	exit
fi

if [ ! -f /mnt/cf/astsrc.tgz ]
then
	/bin/mount /mnt/cf
fi

if [ ! -f /mnt/cf/astsrc.tgz ]
then
	echo "Error: Asterisk source kit not found on flash device"
	exit 1
fi

cd /tmp
/bin/rm -rf configs
echo "Getting archive from flash device (may take a few seconds)"
/bin/tar xzf /mnt/cf/astsrc.tgz configs
/bin/umount /mnt/cf

echo "Copying configuration files"

/bin/cp configs/*.conf /etc/asterisk
/bin/cp configs/$NEWCFG/*.conf /etc/asterisk
/bin/mv /etc/asterisk/zaptel.conf /etc

/bin/rm -f /etc/init.d/$CURCFG
/bin/touch /etc/init.d/$NEWCFG

/bin/rm -rf /tmp/configs

echo "Saving system configuration to flash (make take a moment)"
/usr/local/sbin/svcfg > /dev/null
echo "done"
echo
echo "Configuration changed to $NEWCFG"
echo
exit

