#!/bin/bash
if [ -e /var/bootedfrom ]
then
	. /var/bootedfrom
else
	BOOTEDFROM=/dev/hda1
fi	
umount /mnt/cf >/dev/null 2>/dev/null
mount -t msdos $BOOTEDFROM /mnt/cf || exit 1
cd /
chown -R root:root etc root usr/local
chown root:root home
tar cvzf /mnt/cf/syscfg.tgz etc home root usr/local /usr/src/getsrc /var/www/html /var/spool/cron 
sync
umount /mnt/cf
if [ -x /usr/local/bin/savenode ]
then
	/usr/local/bin/savenode
fi
exit 0
