#!/bin/bash
KVERS=`uname -r`
(cd /; tar cvzf /root/astbin.tgz /lib/modules/${KVERS}/misc \
/usr/lib/libtonezone* /usr/lib/libpri* /usr/lib/asterisk \
/usr/sbin/asterisk /usr/sbin/simpleusb-tune-menu /usr/sbin/radio-tune-menu /sbin/ztcfg /var/lib/asterisk /dev/zap )

