#!/bin/sh
cd /
if [ -e /home/irlp ]
then
	(cd /home/irlp/scripts; su - repeater -c /home/irlp/scripts/backup_for_reinstall)
fi	
tar cf root/backup.tar etc/zaptel.conf etc/asterisk/* var/lib/asterisk/sounds/rpt/nodenames/* etc/network/interfaces
if [ -e /etc/crontabs/root ]
then
	tar rf root/backup.tar etc/crontabs/root
fi
if [ -e /etc/init.d/rc.firewall ]
then
	tar rf root/backup.tar etc/init.d/rc.firewall
fi
if [ -e /home/irlp/backup/irlp_backup.tgz ]
then
	mv /home/irlp/backup/irlp_backup.tgz /root
	tar rf root/backup.tar root/irlp_backup.tgz
fi

(cd /root; rm -rf backup.tgz; gzip -9 backup.tar; mv backup.tar.gz backup.tgz)

if [ -e /root/irlp_backup.tgz ]
then
	rm /root/irlp_backup.tgz
fi		

