#!/bin/bash
tar xvjf syslinux-2.10.tar.bz2
ln -s syslinux-2.10 syslinux
(cd syslinux; make syslinux)
mkdir -p astsrc
(cd astsrc; tar xvzf ../astsrc.tgz)
mkdir -p syscfg
(cd syscfg; tar xvzf ../syscfg.tgz)
mkdir -p rpt_pcm
(cd rpt_pcm; tar xvzf ../rpt_pcm.tgz)

